### ISSUE TITLE
Problem with webpack version, need more detail reporting version issue

### ISSUE THREAD

**Issue by bbarker** [scalacenter/scalajs-bundler#118] opened 2017-04-02 13:15 UTC
Using the following bundler and scala js plugins:

```
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.15")
addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.5.0")
```

I get the report that I'm using an unsupported webpack version in Windows Bash (Ubuntu 14.04), but no details on what versions are supported. I'm using the latest webpack version:

```
> fastOptJS::webpack
[trace] Stack trace suppressed: run last compile:fastOptJS for the full output.
[error] (compile:fastOptJS::scalaJSBundlerWebpackConfig) Unsupported webpack version
[error] Total time: 1 s, completed Apr 2, 2017 1:05:03 PM
> last compile:fastOptJS
java.lang.RuntimeException: Unsupported webpack version
        at scala.sys.package$.error(package.scala:27)
        at scalajsbundler.Webpack$.writeConfigFile(Webpack.scala:64)
        at scalajsbundler.sbtplugin.ScalaJSBundlerPlugin$$anonfun$perScalaJSStageSettings$5.apply(ScalaJSBundlerPlugin.scala:488)
        at scalajsbundler.sbtplugin.ScalaJSBundlerPlugin$$anonfun$perScalaJSStageSettings$5.apply(ScalaJSBundlerPlugin.scala:487)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (compile:fastOptJS::scalaJSBundlerWebpackConfig) Unsupported webpack version
> exit
brandon@DESKTOP-VFD5Q8V:~/projects/mhtml-todo$ webpack --version
2.3.2
```

**Comment by bbarker** [comment] 2017-04-02 13:25
This issue occur on an actual Ubuntu 16.04 system with similar npm/node, but I note now that it seems webpack does not seem to need to be installed globally, so the webpack reported above may not be webpack being used by bundler.

**Comment by julienrf** [comment] 2017-04-02 13:32
What’s the output of `show webpack::version`?

**Comment by bbarker** [comment] 2017-04-02 16:03
@julienrf Thanks - it reports:

```
> webpack::version
[info] 1.14
```

This was the same project directory I was using from Windows IntelliJ. When I checked out the project into a fresh directory using windows bash, I still get the same version but it seems to build without issue:
```
> webpack::version
[info] 1.14
> fastOptJS::webpack
[success] Total time: 1 s, completed Apr 2, 2017 3:59:08 PM
```

That seems to be defined by `./target/scala-2.12/scalajs-bundler/main/package.json` though, so that seems right. 

Perhaps this was just a permission issue - I'll continue to investigate a bit.

**Comment by bbarker** [comment] 2017-04-03 15:35
I think we can close this for now with the recommendation to reclone on Windows, but I will re-open if the issue proves inconvenient or worse than I thought.

**Comment by KadekM** [comment] 2017-05-15 11:54
I am suffering same problem with `0.6.16` and `0.6` bundler on Ubuntu 16.04. Any advice other than to reclone it in Windows?

**Comment by julienrf** [comment] 2017-05-15 11:56
Can you show me the output of the `webpack::version` sbt task?

**Comment by KadekM** [comment] 2017-05-15 11:57
```
sample> show webpack::version
[info] sample/*:webpack::version
[info] 	1.14
```

**Comment by KadekM** [comment] 2017-05-16 08:00
@julienrf Could you give me some pointers what should I try to try to make this work or to provide more info? Could we re-open this issue?
It works on my osx.

**Comment by julienrf** [comment] 2017-05-17 10:49
Hi, yes we should re-open the issue. I have no time currently to have a look at the problem…

**Comment by jonas** [comment] 2017-06-18 14:33
The problem seems to be that `webpack` is not installed into `node_modules`. In the generated `package.json` file it is listed as a `devDependency` and NPM dependencies are installed using `npm update`, which won't install `devDependencies` by default, from the [npm update docs](https://docs.npmjs.com/cli/update) :

> It will also install missing packages. As with all commands that install packages, the --dev flag will cause devDependencies to be processed as well.

Not sure if this is a change in how `npm update` works or how this plugin works. Enabling Yarn fixes this.

I don't have `webpack` installed (`npm install -g webpack`) on my machine.
NPM version info:
```
> npm version
{ npm: '5.0.3',
  ares: '1.10.1-DEV',
  cldr: '30.0.3',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '57',
  node: '8.1.0',
  openssl: '1.0.2l',
  tz: '2016j',
  unicode: '9.0',
  uv: '1.12.0',
  v8: '5.8.283.41',
  zlib: '1.2.11' }
```

**Comment by danxmoran** [comment] 2017-07-10 21:46
I've hit the same problem while trying to get up and running, and have been poking around trying to find a fix. My `npm version` is exactly the same as @jonas's. Here's what I've found so far:

1. If I clone this repo and run `scripted`, every test that doesn't enable yarn fails with the "invalid webpack version" error.
2. If I add the `--dev` flag [here](https://github.com/scalacenter/scalajs-bundler/blob/master/sbt-scalajs-bundler/src/main/scala/scalajsbundler/sbtplugin/ScalaJSBundlerPlugin.scala#L571), nothing changes.
3. If I add `--save-dev` or `-D` instead of `--dev`, the tests still fail, but they fail with "cannot find module" errors. It looks like npm *only* downloads dev dependencies when these flags are given.
4. We might be running up against npm/npm#16901.

@julienrf what version of npm do you / the CI use when testing the plugin? I can't find anything in the code / docs.

**Comment by julienrf** [comment] 2017-07-11 09:43
Thanks @danxmoran for the investigation. My npm version is 4.2.0.

**Comment by danxmoran** [comment] 2017-07-11 13:58
Thanks for the info @julienrf! I can confirm that reverting to npm 4.2.0 gets all the scripted tests to pass for me. I think it'd be good to add a note to the docs / README stating that you designed against 4.2, and that breaking changes in 5.x have caused problems.

Personally I think it'd be cool to go one step further and have the plugin pull down and use known good versions of npm / yarn (similar to [this](https://github.com/typesafehub/npm/blob/master/src/main/scala/com/typesafe/npm/Npm.scala#L54)). There are webjars for npm 4.2.0 and yarn 0.23.2 that we could use.

I'd be happy to contribute either, just let me know if you'd prefer docs-only or if I should investigate the webjar approach!

**Comment by julienrf** [comment] 2017-07-11 17:10
Currently the plugin uses the npm executable of the host environment but that could be an interesting idea to embed a version of npm that we know works well with the plugin. On the other hand, that might be more work to support both 4.x and 5.x but that might also be more convenient if some users want to use some specific features of npm 5.x…

So, I’m not sold on the approach to take here :)

**Comment by danxmoran** [comment] 2017-07-11 21:33
Just throwing ideas out: What if the plugin embedded a known-to-work version of npm and yarn, but then provided escape-hatch settings to let users switch over to the executables in the host environment? That way users without much exposure to npm can expect the plugin to "just work", and the adventurous can opt-in to trying out newer versions.

**Comment by julienrf** [comment] 2017-07-12 10:58
Yes that would be a good solution. I’m a bit afraid by the complexity that would be added, though.

**Comment by DavidWhit** [comment] 2017-07-28 14:32
I just ran into this issue on windows using intellij and had to run npm install or to be specific 
from target/scala-2.12/main using webpack 1.14 in the package.json on npm 5.0.3
then 
    reload
then
    fastOptJS::webpack
Strange because I'm not sure what got me here as I have another project on my desktop that worked without issue.

**Comment by easel** [comment] 2017-08-31 20:34
Unless we run into some other issues with it, this issue should have been resolved by https://github.com/scalacenter/scalajs-bundler/pull/172.

**Comment by julienrf** [comment] 2017-09-10 08:39
Can we close this issue?

**Comment by jacobm** [comment] 2017-09-20 05:58
I ran into this error after clearing out my client/target folder.

Deleting my node_modules folder made scalajsbunder install all dependencies and seemed to trigger the full build pipeline - and sorted out the webpack issue for me.

**Comment by DavidWhit** [comment] 2017-09-20 19:36
​Sorry, if you're asking I'm good if it's closed​

**Comment by julienrf** [comment] 2017-09-20 21:04
Thanks :)

**Closed** 2017-09-20 21:04 UTC
Labels: bug
