### ISSUE TITLE
NoSuchElementException when using fastOptJs

### ISSUE THREAD

**Issue by nnovod-umms** [scalacenter/scalajs-bundler#384] opened 2020-11-19 16:44 UTC
When trying to do a fastOptJS for my Scala.js client code I get a NoSuchElementException.

I'm using plugins sbt-scalajs 1.3.1 and sbt-scalajs-bundler 0.20.0 with sbt 1.4.3
The build.sbt file and error is:
`
[IJ]last Compile / fastOptJS
[error] java.util.NoSuchElementException: head of empty list
[error] 	at scala.collection.immutable.Nil$.head(List.scala:469)
[error] 	at scala.collection.immutable.Nil$.head(List.scala:466)
[error] 	at org.scalajs.sbtplugin.ScalaJSPluginInternal$.$anonfun$scalaJSStageSettings$24(ScalaJSPluginInternal.scala:296)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:745)
[error] (Compile / fastOptJS) java.util.NoSuchElementException: head of empty list
`

The build.sbt file is...
lazy val scalaVer = "2.13.3"
lazy val akkaVersion = "2.6.9"
lazy val akkaHttpVersion = "10.2.1"
lazy val scalaTagsVersion = "0.9.2"
lazy val scalaJSVersion = "1.3.1"
lazy val scalaJSDomVersion = "1.1.0"
lazy val scalaJSReactVersion = "1.7.6"

ThisBuild / scalaVersion := scalaVer

def akkaDeps = Seq(
  "com.typesafe.akka" %% "akka-stream" % akkaVersion withSources(),
  "com.typesafe.akka" %% "akka-http" % akkaHttpVersion withSources(),
  "com.typesafe.akka" %% "akka-actor-typed" % akkaVersion withSources()
)

lazy val root = (project in file("."))
  .aggregate(lims, limsJS)
  
lazy val lims = (project in file("LIMS"))
  .settings(
    name := "lims",
    libraryDependencies ++= akkaDeps,
    libraryDependencies += "com.lihaoyi" %% "scalatags" % scalaTagsVersion withSources()
  )

lazy val limsJS = (project in file("LIMSjs"))
  .enablePlugins(ScalaJSPlugin, ScalaJSBundlerPlugin)
  .settings(
    name := "limsJS",
    libraryDependencies ++= Seq(
      "org.scala-js" %%% "scalajs-dom" % scalaJSDomVersion withSources(),
      "com.lihaoyi" %%% "scalatags" % scalaTagsVersion withSources(),
      "com.github.japgolly.scalajs-react" %%% "core" % scalaJSReactVersion withSources()
    ),
    npmDependencies in Compile ++= Seq(
      "react" -> "16.13.1",
      "react-dom" -> "16.13.1"
    )
  )

Any help appreciated.

Thank you,
Nathaniel

**Comment by sjrd** [comment] 2020-11-19 17:10
Duplicate of https://github.com/scala-js/scala-js/issues/4295.

Please do not post the same issue twice, or at least mention in the issue that there is another report in a different repo. Don't make us guess and potentially do twice the work.

**Closed by sjrd** 2020-11-19 17:10 UTC

**Comment by nnovod-umms** [comment] 2020-11-19 17:13
Sorry - I was about to close this one because I realized that it was not associated with the bundler.
