### ISSUE TITLE
missing fastopt.js file

### ISSUE THREAD

**Issue by bbarker** [scalacenter/scalajs-bundler#117] opened 2017-03-31 17:50 UTC
Not quite sure what I'm doing wrong, as when I compare it to a similar project, everything looks right. Here's the error:

```
[info] Bundling the application with its NPM dependencies
[info] Hash: c3f81c29c9363bfcb6a7
[info] Version: webpack 1.14.0
[info] Time: 146ms
[info]                            Asset     Size  Chunks             Chunk Names
[info]     mhtml-todo-fastopt-bundle.js  1.85 kB       0  [emitted]  mhtml-todo-fastopt
[info] mhtml-todo-fastopt-bundle.js.map  1.79 kB       0  [emitted]  mhtml-todo-fastopt
[info]     + 1 hidden modules
[info] 
[info] ERROR in ./fastopt-launcher.js
[info] Module not found: Error: Cannot resolve 'file' or 'directory' C:\Users\brand\Documents\GitHub\mhtml-todo\target\scala-2.12\scalajs-bundler\main\mhtml-todo-fastopt.js in C:\Users\brand\Documents\GitHub\mhtml-todo\target\scala-2.12\scalajs-bundler\main
[info]  @ ./fastopt-launcher.js 1:0-124
[success] Total time: 4 s, completed Mar 31, 2017 1:45:56 PM
```

Indeed, the `mhtml-todo-fastopt.js` is not present. In another project, the contents of the analogous `*fastopt.js` seem to be embedded in `*fastopt-bundle.js`, but in this project, I see the following in `mhtml-todo-fastopt.js`:

```js
	__webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"C:\\Users\\brand\\Documents\\GitHub\\mhtml-todo\\target\\scala-2.12\\scalajs-bundler\\main\\mhtml-todo-fastopt.js\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()))["mhtml"]["todo"]["MhtmlTodo"]().main()
```

My build.sbut:

```scala
enablePlugins(ScalaJSPlugin, ScalaJSBundlerPlugin)

name := "mhtml-todo"

scalaVersion := "2.12.1" // or any other Scala version >= 2.10.2
lazy val mhtmlV = "0.3.0"

//libraryDependencies += "in.nvilla" %%% "monadic-rx-cats" % mhtmlV
libraryDependencies += "in.nvilla" %%% "monadic-html" % mhtmlV
libraryDependencies += "com.lihaoyi" %%% "upickle" % "0.4.4"

requiresDOM in Test := true
webpackConfigFile in fastOptJS := Some(baseDirectory.value / "dev.webpack.config.js")
npmDependencies in Compile += "todomvc-common" -> "1.0.3"
```

plugins.sbt:

```scala
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.15")
addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.5.0")
```

**Comment by garhirunrat** [comment] 2017-04-01 10:46
Hi @bbarker 
Can I see your dev.webpack.config.js?
I see there is nothing wrong with scalajs-bundler.
https://github.com/garhirunrat/scalajs-tutorial/tree/scalajs-bundler
```
[info] Bundling the application with its NPM dependencies
[info] Hash: 9922699ebe6c1141648d
[info] Version: webpack 1.14.0
[info] Time: 408ms
[info]                                   Asset     Size  Chunks             Chunk Names
[info]     scala-js-tutorial-fastopt-bundle.js  85.2 kB       0  [emitted]  scala-js-tutorial-fastopt
[info] scala-js-tutorial-fastopt-bundle.js.map  35.4 kB       0  [emitted]  scala-js-tutorial-fastopt
[info]     + 2 hidden modules
...
[success] Total time: 30 s, completed Apr 1, 2017 5:32:24 PM
```

**Comment by bbarker** [comment] 2017-04-01 12:21
Thanks @garhirunrat 

I used a similar, minimal file on another project seemingly without issue:

```js
var webpack = require('webpack');

module.exports = require('./scalajs.webpack.config');
module.exports.plugins = (module.exports.plugins || []);
```

Also, the output of `scalajs.webpack.config.js` looks like:

```js
module.exports = {
  "entry": {
    "mhtml-todo-fastopt": "C:\\Users\\brand\\Documents\\GitHub\\mhtml-todo\\target\\scala-2.12\\scalajs-bundler\\main\\fastopt-launcher.js"
  },
  "output": {
    "path": "C:\\Users\\brand\\Documents\\GitHub\\mhtml-todo\\target\\scala-2.12\\scalajs-bundler\\main",
    "filename": "[name]-bundle.js"
  },
  "devtool": "source-map",
  "module": {
    "preLoaders": [{
      "test": new RegExp("\\.js$"),
      "loader": "source-map-loader"
    }]
  }
}
```

**Comment by bbarker** [comment] 2017-04-01 12:27
@garhirunrat Also, I posted the current state of the repo in this branch: https://github.com/bbarker/mhtml-todo/tree/bundler_wip

**Comment by garhirunrat** [comment] 2017-04-01 16:25
I ran `sbt fastOptJS::webpack` on https://github.com/bbarker/mhtml-todo/tree/bundler_wip and it built `success` for me.

fastopt.js file is not missing.

![screenshot 2017-04-01 23 21 25](https://cloud.githubusercontent.com/assets/16944868/24580428/3aefea04-1732-11e7-8297-ea9a2db533ec.png)

**Comment by julienrf** [comment] 2017-04-01 19:12
@garhirunrat Are you using Windows too? I remember that I had lots of troubles on windows because some files were missing at some point in the process, but I was never able to reproduce the problem in a reliable way. Maybe @bbarker found a way to systematically reproduce the problem!

**Comment by garhirunrat** [comment] 2017-04-01 19:19
@julienrf Oh cool! 
No, I'm on Mac.

**Comment by bbarker** [comment] 2017-04-01 19:52
Yep, I'm on Windows; hadn't tried this project on another OS yet.

**Comment by bbarker** [comment] 2017-04-02 13:29
I tried on Windows bash ( #118 ) but ran into other issues. After trying in Ubuntu I can also confirm not issues. I have the same issues on more than one Windows system (both Windows 10).

**Comment by bbarker** [comment] 2017-04-02 16:18
I cloned the repo into a different directory and ran afresh - this time, all worked from sbt in Windows IntelliJ (as well as Windows Bash). Will keep looking into the problems in the old directories on each system to see if I can learn a bit more.

**Comment by bbarker** [comment] 2017-04-03 15:17
Back on my original system, I ran `sbt fastOptJS::webpack` from IntelliJ: same problem. I then tried it in Windows Bash (same project) directory and it worked. After that, I couldn't reproduce the problem! After doing an `sbt clean`, and running `sbt fastOptJS::webpack` from IntelliJ ... all was well. Still fairly mysterious, but at least it seems somewhat easy to get around.

**Comment by julienrf** [comment] 2019-04-16 08:07
I’m closing this issue since it doesn’t seem to still happen now.

**Closed by julienrf** 2019-04-16 08:07 UTC
