### ISSUE TITLE
webpack 4.0.0. with scalajs Bundler  "0.13.1"

### ISSUE THREAD

**Issue by ashu2012** [scalacenter/scalajs-bundler#263] opened 2018-09-13 10:38 UTC
webpack is intsalled but scalajs bundler saying webpack version not ofund. Commandline webpack is also working

`
C:\Users\h217119\IdeaProjects\ScalaJsWebApp>webpack
Hash: 41b41fe2d221a185b1ad
Version: webpack 4.0.0
Time: 67ms
Built at: 9/13/2018 4:02:33 PM

WARNING in configuration
The 'mode' option has not been set. Set 'mode' option to 'development' or 'production' to enable defaults for this environment.

ERROR in Entry module not found: Error: Can't resolve './src' in 'C:\Users\h217119\IdeaProjects\ScalaJsWebApp'

`

`[info] Writing scalajs.webpack.config.js
java.lang.RuntimeException: No webpack version defined
        at scala.sys.package$.error(package.scala:27)
        at scalajsbundler.Webpack$.writeConfigFile(Webpack.scala:153)
        at scalajsbundler.Webpack$.bundle(Webpack.scala:185)
        at scalajsbundler.sbtplugin.WebpackTasks$$anonfun$webpack$1$$anonfun$1.apply(WebpackTasks.scala:40)
        at scalajsbundler.sbtplugin.WebpackTasks$$anonfun$webpack$1$$anonfun$1.apply(WebpackTasks.scala:39)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
        at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:267)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:263)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:206)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:263)
        at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:262)
        at sbt.Difference.apply(Tracked.scala:224)
        at sbt.Difference.apply(Tracked.scala:200)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:262)
        at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:260)
        at scalajsbundler.sbtplugin.WebpackTasks$$anonfun$webpack$1.apply(WebpackTasks.scala:52)
        at scalajsbundler.sbtplugin.WebpackTasks$$anonfun$webpack$1.apply(WebpackTasks.scala:20)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[error] (compile:fastOptJS::webpack) No webpack version defined
[error] Total time: 5 s, completed Sep 13, 2018 3:39:21 PM`

**Comment by julienrf** [comment] 2018-09-13 12:36
scalajs-bundler locally installs webpack (to not interfere with what you have on your system). Do you have a `target/scalajs-bundler/main/node_modules/webpack/package.json` file?

**Comment by julienrf** [comment] 2018-11-12 08:18
I’m closing this issue because we don’t have enough information to reproduce it. Feel free to re-open it with more details!

**Closed by julienrf** 2018-11-12 08:18 UTC
